name: SAMPL-hello-world
channels:
  - openeye
  - rdkit
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=20.3.0=pyhd3eb1b0_0
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py38h06a4308_0
  - iniconfig=1.1.1=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - openeye-toolkits=2020.2.0=py38_0
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.8=pyhd3eb1b0_0
  - pip=20.3.3=py38h06a4308_0
  - pluggy=0.13.1=py38_0
  - py=1.10.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pytest=6.2.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.0=h7b6447c_0
  - setuptools=51.0.0=py38h06a4308_2
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - black==20.8b1
    - click==7.1.2
    - isort==5.6.4
    - mypy-extensions==0.4.3
    - pathspec==0.8.1
    - regex==2020.11.13
    - scripttest==1.3
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.3
